package model;

public enum CompanyEnum {
	APPLE,
	THINKING_MACHINES,
	RCA,
	Netronics,
	Tandy,
	Commodore,
	MOS, 
	Tandy_Corporation,
	Commodore_International,
	MOS_Technology,
	Micro_Instrumentation_and_Telemetry_Systems,
	IMS_Associates,
	Digital_Equipment_Corporation,
	Lincoln_Laboratory,
	Moore_School_of_Electrical_Engineering ,
	IBM,
	Amiga_Corporation,                     
	Canon,                                       
	Nokia ,                                      
	Sony   ,                                     
	OQO,
	NeXT,
	Atari ,                                      
	Acorn_computer,                              
	Timex_Sinclair,                              
	Nintendo,                                    
	Sinclair_Research_Ltd,                       
	Xerox,
	Hewlett_Packard,                             
	Zemmix,
	ACVS,
	Sanyo,
	Cray,
	Evans_And_Sutherland,
	ESR,
	OMRON,
	BBN_Technologies,
	Lenovo_Group,
	ASUS,
	Amstrad,
	Sun_Microsystems,
	Texas_Instruments,
	HTC_Corporation,
	Research_In_Motion,
	Samsung_Electronics  
}
